services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: laravel
        uid: 1000
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    networks:
      - laravel
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: storageManager
      POSTGRES_USER: storageOwner
      POSTGRES_PASSWORD: secretfellas
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  pgdata: